import os
import re
import joblib
import numpy as np
import pandas as pd
from flask import Flask, jsonify, request, send_from_directory
from flask_cors import CORS
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# Import text cleaning function
from text_utils import clean_resume

app = Flask(__name__)
CORS(app)

# --------------------------------------------------------- Model Loading & Fallback
# We search for the files generated by the Colab training script or previous steps.
MODEL_PATH = "resume_model (1).pkl" if os.path.exists("resume_model (1).pkl") else "resume_model.pkl"
VEC_PATH = "tfidf_vectorizer (1).pkl" if os.path.exists("tfidf_vectorizer (1).pkl") else "tfidf_vectorizer.pkl"
BUNDLE_PATH = "resume_classifier_bundle.joblib"

model = None
vectorizer = None
model_name = "Mock-Fallback Classifier"
labels = []

def train_fallback_model():
    """Train a quick, lightweight fallback model if no weights are found."""
    print("\n[WARNING] No pre-trained model found! Auto-training a fallback model...")
    # Minimal training data covering main categories
    fallback_data = [
        # Data Science
        ("Data Scientist with Python, SQL, machine learning, pandas, scikit-learn, stats, and tensorflow experience.", "Data Science"),
        ("Machine learning engineer specializing in NLP, Deep learning, neural networks, PyTorch and Python data analysis.", "Data Science"),
        # Web Developer / Designing
        ("Frontend Web Developer skilled in HTML, CSS, JavaScript, React, Node.js, and responsive UI design.", "Web Designing"),
        ("Full-stack web engineer. Skilled in React, express.js, MongoDB, bootstrap, frontend and backend development.", "Web Designing"),
        # Java Developer
        ("Java developer with Spring Boot, Hibernate, microservices, Maven, REST APIs, and SQL experience.", "Java Developer"),
        ("Backend software engineer. Expert in Java 11, OOP principles, multithreading, and postgresql database design.", "Java Developer"),
        # HR
        ("HR recruiter specializing in full-cycle recruitment, talent acquisition, employee relations, and onboarding.", "HR"),
        ("Human Resources Manager. Sourced candidates, managed payroll, compliance, and training programs.", "HR"),
        # Accounting
        ("Senior Accountant experienced in auditing, tax declaration, general ledger, invoice reconciliation, and Excel spreadsheets.", "ACCOUNTANT"),
        ("Financial accountant. Handled balance sheet audits, quickbooks accounting, taxation, and budgeting.", "ACCOUNTANT"),
        # Engineering
        ("Mechanical engineer proficient in CAD design, SolidWorks modeling, product manufacturing, and structural analysis.", "ENGINEERING"),
        ("Project engineer. Managed civil engineering construction layouts, manufacturing processes, and technical planning.", "ENGINEERING")
    ]
    
    texts = [clean_resume(item[0]) for item in fallback_data]
    categories = [item[1] for item in fallback_data]
    
    # Train tf-idf and classifier
    vec = TfidfVectorizer(max_features=500, ngram_range=(1, 2))
    X_vec = vec.fit_transform(texts)
    
    clf = LogisticRegression(class_weight="balanced")
    clf.fit(X_vec, categories)
    
    # Save fallback
    joblib.dump(clf, MODEL_PATH)
    joblib.dump(vec, VEC_PATH)
    print("[SUCCESS] Fallback model trained and saved successfully.\n")
    return clf, vec

# Attempt to load models in order of availability
if os.path.exists(MODEL_PATH) and os.path.exists(VEC_PATH):
    try:
        model = joblib.load(MODEL_PATH)
        vectorizer = joblib.load(VEC_PATH)
        model_name = "Optimized Classifier (resume_model.pkl)"
        # Get labels from model classes if available
        if hasattr(model, "classes_"):
            labels = list(model.classes_)
        print(f"Loaded model and vectorizer from local PKL files: {model_name}")
    except Exception as e:
        print(f"Error loading local PKL files: {e}")

if model is None and os.path.exists(BUNDLE_PATH):
    try:
        bundle = joblib.load(BUNDLE_PATH)
        model = bundle["model"]
        vectorizer = bundle["vectorizer"]
        model_name = bundle.get("model_name", "Trained Bundle Classifier")
        labels = bundle.get("labels", [])
        print(f"Loaded model bundle: {model_name}")
    except Exception as e:
        print(f"Error loading bundle: {e}")

if model is None:
    # If no model weights are found anywhere, auto-train a minimal model so app works
    model, vectorizer = train_fallback_model()
    labels = list(model.classes_)

# --------------------------------------------------------- Resume Scorer & Analyzer
# Category-specific keywords for detailed resume rating matches
ROLE_KEYWORDS = {
    "DATA SCIENCE": ["python", "sql", "machine learning", "stats", "deep learning", "r", "pandas", "numpy", "scikit-learn", "tensorflow", "pytorch", "regression", "clustering", "visualization", "nlp"],
    "WEB DESIGNING": ["html", "css", "javascript", "react", "angular", "vue", "node", "express", "bootstrap", "git", "api", "responsive", "frontend", "backend", "web"],
    "JAVA DEVELOPER": ["java", "spring", "boot", "hibernate", "maven", "microservices", "sql", "oop", "multithreading", "jpa", "rest api"],
    "HR": ["human resources", "recruitment", "hiring", "onboarding", "payroll", "talent", "compliance", "employee", "training", "ats", "interview"],
    "ENGINEERING": ["engineering", "cad", "design", "solidworks", "manufacturing", "process", "technical", "project", "analysis"],
    "ACCOUNTANT": ["accounting", "audit", "tax", "ledger", "finance", "balance", "reconciliation", "excel", "quickbooks", "invoice"],
    "SALES": ["sales", "customer", "target", "revenue", "marketing", "leads", "pipeline", "client", "negotiation"],
    "TEACHER": ["teaching", "education", "classroom", "students", "curriculum", "lesson", "learning", "school", "instruction"],
    "ADVOCATE": ["legal", "law", "court", "case", "research", "litigation", "contract", "defense", "counsel"]
}

# General action verbs that make resumes stronger
ACTION_VERBS = ["led", "developed", "managed", "designed", "implemented", "created", "increased", "optimized", "built", "spearheaded", "engineered", "collaborated", "formulated", "coordinated", "resolved"]

def predict_with_confidence(text: str):
    cleaned = clean_resume(text)
    vector = vectorizer.transform([cleaned])
    prediction = model.predict(vector)[0]

    # Handle confidence probability extraction safely using temperature scaling (T=5)
    if hasattr(model, "decision_function"):
        scores = model.decision_function(vector)[0]
        if hasattr(scores, "__len__") and len(scores) > 1:
            exp_scores = np.exp(5 * (scores - scores.max()))
            probs = exp_scores / exp_scores.sum()
            confidence = float(probs.max())
        else:
            val = float(scores[0]) if hasattr(scores, "__len__") else float(scores)
            confidence = float(1.0 / (1.0 + np.exp(-5 * abs(val))))
    elif hasattr(model, "predict_proba"):
        probs = model.predict_proba(vector)[0]
        confidence = float(probs.max())
    else:
        confidence = 0.50

    return prediction, confidence

def analyze_resume_text(text: str, category: str):
    """Rate the resume, check structural completeness, and give suggestions."""
    suggestions = []
    
    # 1. Structural Checks (Search for section markers)
    has_contact = bool(re.search(r"(\S+@\S+|\d{3}-\d{3}-\d{4}|\+?\d[\d -]{8,12}\d)", text))
    
    text_lower = text.lower()
    has_education = any(keyword in text_lower for keyword in ["education", "degree", "university", "college", "school", "bachelor", "master", "phd"])
    has_experience = any(keyword in text_lower for keyword in ["experience", "work history", "employment", "professional background", "job history", "career"])
    has_skills = any(keyword in text_lower for keyword in ["skills", "expertise", "technologies", "proficiencies", "core competencies"])
    has_projects = any(keyword in text_lower for keyword in ["projects", "personal projects", "portfolio", "key projects"])

    structure_score = 0
    if has_contact: structure_score += 10
    else: suggestions.append("Add email address, phone number or LinkedIn profile link.")
        
    if has_education: structure_score += 10
    else: suggestions.append("Create a dedicated 'Education' section outlining your qualifications.")
        
    if has_experience: structure_score += 10
    else: suggestions.append("Add a detailed 'Experience' section outlining your professional work history.")
        
    if has_skills: structure_score += 10
    else: suggestions.append("Add a 'Skills' section listing your technical and soft proficiencies.")
        
    if has_projects: structure_score += 10
    else: suggestions.append("Add a 'Projects' section to showcase practical applications of your skills.")

    # 2. Content & Writing Quality
    words = text_lower.split()
    word_count = len(words)
    content_score = 25 # Start with default points
    
    if word_count < 150:
        content_score = 10
        suggestions.append("Your resume text is very short. Expand on your responsibilities, achievements, and descriptions.")
    elif word_count > 1000:
        content_score = 15
        suggestions.append("Your resume is extremely long. Try to summarize descriptions and keep it concise (under 800 words).")
        
    # Check for strong action verbs
    found_verbs = [verb for verb in ACTION_VERBS if verb in text_lower]
    verb_score = min(len(found_verbs) * 2, 10) # Max 10 points
    if len(found_verbs) < 4:
        suggestions.append("Incorporate more strong action verbs (e.g., 'managed', 'designed', 'optimized') in your experience details.")

    # 3. Role-specific Keyword Match
    normalized_category = category.upper().replace("-", " ")
    match_keywords = []
    
    # Try direct lookup, or search for partial role match
    role_keys = []
    for k, v in ROLE_KEYWORDS.items():
        if k in normalized_category or normalized_category in k:
            role_keys = v
            break
            
    if not role_keys:
        role_keys = ["professional", "experience", "skills", "teamwork", "management", "technical", "projects"]

    matched_keys = [key for key in role_keys if key in text_lower]
    keyword_score = 0
    if role_keys:
        keyword_score = min(int((len(matched_keys) / len(role_keys)) * 25), 25)
        
    missing_keys = [key for key in role_keys if key not in text_lower]
    if missing_keys:
        suggest_keys = ", ".join(missing_keys[:4])
        suggestions.append(f"Enhance your resume by including keywords relevant to {category}: {suggest_keys}.")

    # Calculate overall score
    overall_score = structure_score + content_score + verb_score + keyword_score
    overall_score = min(max(overall_score, 10), 100) # Clamp between 10% and 100%

    if overall_score >= 85 and not suggestions:
        suggestions.append("Your resume is well-structured and contains relevant keywords. Try tailoring it to specific job descriptions.")

    return {
        "overall_score": overall_score,
        "structure_score": structure_score,
        "content_score": content_score,
        "keyword_score": keyword_score,
        "structure_check": {
            "has_contact": has_contact,
            "has_education": has_education,
            "has_experience": has_experience,
            "has_skills": has_skills,
            "has_projects": has_projects
        },
        "matched_keywords": matched_keys,
        "suggestions": suggestions
    }

# --------------------------------------------------------- API Routes
@app.route("/predict", methods=["POST"])
def predict():
    data = request.get_json(silent=True) or {}
    text = (data.get("resume_text") or "").strip()

    if not text:
        return jsonify({"error": "resume_text is required"}), 400

    category, confidence = predict_with_confidence(text)
    return jsonify({
        "category": category,
        "confidence": confidence,
        "model_used": model_name,
    })

@app.route("/analyze", methods=["POST"])
def analyze():
    data = request.get_json(silent=True) or {}
    text = (data.get("resume_text") or "").strip()

    if not text:
        return jsonify({"error": "resume_text is required"}), 400

    category, confidence = predict_with_confidence(text)
    analysis = analyze_resume_text(text, category)
    
    return jsonify({
        "category": category,
        "confidence": confidence,
        "model_used": model_name,
        "analysis": analysis
    })

@app.route("/health", methods=["GET"])
def health():
    return jsonify({
        "status": "ok", 
        "model": model_name,
        "categories_supported": labels
    })

# --------------------------------------------------------- Candidate Database Helpers
CANDIDATES_FILE = "candidates.json"

def read_candidates():
    import json
    if not os.path.exists(CANDIDATES_FILE):
        return []
    try:
        with open(CANDIDATES_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        print(f"Error reading candidates file: {e}")
        return []

def write_candidates(candidates):
    import json
    try:
        with open(CANDIDATES_FILE, "w", encoding="utf-8") as f:
            json.dump(candidates, f, indent=4)
        return True
    except Exception as e:
        print(f"Error writing candidates file: {e}")
        return False

# --------------------------------------------------------- Candidate API Routes
@app.route("/api/candidates", methods=["POST"])
def add_candidate():
    import uuid
    from datetime import datetime
    
    data = request.get_json(silent=True) or {}
    name = (data.get("name") or "").strip()
    email = (data.get("email") or "").strip()
    phone = (data.get("phone") or "").strip()
    category = (data.get("category") or "").strip()
    score = data.get("score")
    resume_text = (data.get("resume_text") or "").strip()
    
    if not name or not category:
        return jsonify({"error": "Candidate name and category are required"}), 400
        
    # Auto-extract contact info using regex if missing
    if not email:
        email_match = re.search(r"([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)", resume_text)
        if email_match:
            email = email_match.group(1).strip()
            
    if not phone:
        phone_match = re.search(r"(\+?\d[\d -]{8,12}\d)", resume_text)
        if phone_match:
            phone = phone_match.group(1).strip()
            
    try:
        score_val = int(float(score)) if score is not None else 70
    except ValueError:
        score_val = 70
        
    candidates = read_candidates()
    
    if email:
        existing = next((c for c in candidates if c.get("email") == email), None)
        if existing:
            return jsonify({"error": f"Candidate with email '{email}' is already registered."}), 400
            
    new_candidate = {
        "id": str(uuid.uuid4()),
        "name": name,
        "email": email,
        "phone": phone,
        "category": category,
        "score": score_val,
        "date_added": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "resume_text": resume_text[:10000]
    }
    
    candidates.append(new_candidate)
    if write_candidates(candidates):
        return jsonify(new_candidate), 201
    else:
        return jsonify({"error": "Failed to save candidate"}), 500

@app.route("/api/candidates", methods=["GET"])
def get_candidates():
    candidates = read_candidates()
    return jsonify(candidates)

@app.route("/api/candidates/<candidate_id>", methods=["DELETE"])
def delete_candidate(candidate_id):
    candidates = read_candidates()
    filtered = [c for c in candidates if c.get("id") != candidate_id]
    
    if len(filtered) == len(candidates):
        return jsonify({"error": "Candidate not found"}), 404
        
    if write_candidates(filtered):
        return jsonify({"message": "Candidate deleted successfully"})
    else:
        return jsonify({"error": "Failed to delete candidate"}), 500

@app.route("/api/candidates/export", methods=["GET"])
def export_candidates():
    import io
    from flask import Response
    
    candidates = read_candidates()
    
    output = io.StringIO()
    output.write("Name,Email,Phone,Predicted Category,Score,Date Registered\n")
    
    for c in candidates:
        name = f'"{c.get("name", "")}"'
        email = f'"{c.get("email", "")}"'
        phone = f'"{c.get("phone", "")}"'
        cat = f'"{c.get("category", "")}"'
        score = c.get("score", "")
        date = f'"{c.get("date_added", "")}"'
        output.write(f"{name},{email},{phone},{cat},{score},{date}\n")
        
    csv_data = output.getvalue()
    return Response(
        csv_data,
        mimetype="text/csv",
        headers={"Content-disposition": "attachment; filename=candidates_export.csv"}
    )

@app.route("/api/ai/chat", methods=["POST"])
def ai_chat():
    data = request.get_json(silent=True) or {}
    message = (data.get("message") or "").strip()
    category = (data.get("category") or "").strip().upper()
    
    if not message:
        return jsonify({"error": "Message is required"}), 400
        
    if not category:
        category = "INFORMATION-TECHNOLOGY"
        
    normalized_cat = category.replace("-", " ")
    
    # Specific pre-defined roles dictionary
    specific_data = {
        "INFORMATION-TECHNOLOGY": {
            "summaries": [
                "Passionate Software Engineer and IT Specialist with 5+ years of experience building scalable, high-performance web applications and cloud architectures.",
                "Detail-oriented Developer proficient in Java, Spring Boot, Python, SQL databases, and modern JavaScript frameworks. Strong advocate for clean code and agile development.",
                "Full-Stack IT professional with a background in designing responsive user interfaces, configuring backend APIs, and implementing automated testing pipelines."
            ],
            "bullets": [
                "Led a team of developers to build robust web services using Python, Flask, and PostgreSQL, increasing performance by 25%.",
                "Optimized database query models and implemented indexing strategies, reducing server latency by 35%.",
                "Designed and maintained responsive frontend components using HTML5, CSS3, JavaScript, and React, enhancing user experience.",
                "Coordinated deployment pipelines using Git and CI/CD tools to deliver features with zero downtime."
            ],
            "skills": ["Java", "Python", "SQL", "Spring Boot", "Flask", "React", "HTML5/CSS3", "Git", "REST APIs", "Agile Development"]
        },
        "HR": {
            "summaries": [
                "Dedicated HR Specialist with expertise in full-cycle recruitment, talent acquisition, employee relations, and employee onboarding programs.",
                "Human Resources Manager skilled in conflict resolution, compliance, benefits administration, and training program execution.",
                "Strategic HR professional focused on developing workplace cultures, optimizing ATS tools, and sourcing top-tier talent."
            ],
            "bullets": [
                "Managed end-to-end recruitment for technical and non-technical roles, reducing average time-to-hire by 18%.",
                "Facilitated employee onboarding and developed structured training programs to accelerate new hire productivity.",
                "Resolved employee grievances and implemented performance evaluation processes to improve retention.",
                "Ensured compliance with company policies and local labor regulations, conducting periodic audits."
            ],
            "skills": ["Talent Acquisition", "Employee Relations", "ATS Management", "Onboarding", "Conflict Resolution", "Labor Compliance"]
        },
        "ACCOUNTANT": {
            "summaries": [
                "Detail-oriented Certified Accountant with extensive experience in financial reporting, tax preparation, general ledger reconciliation, and auditing.",
                "Senior Accountant skilled in QuickBooks, advanced Excel formulas, budget forecasting, and balance sheet analysis.",
                "Financial Accountant with a track record of preparing audit documents, reducing financial errors, and implementing efficient invoice management."
            ],
            "bullets": [
                "Managed general ledger entries, balance sheet reconciliations, and monthly financial statement preparation.",
                "Prepared comprehensive corporate tax declarations and audited account logs, ensuring 100% regulatory compliance.",
                "Analyzed budget variances and worked with management to implement cost-saving measures, saving $15k annually.",
                "Automated invoice processing systems, decreasing monthly accounting closing cycles by 3 days."
            ],
            "skills": ["QuickBooks", "General Ledger", "Tax Declaration", "Financial Auditing", "Budget Forecasting", "Advanced Excel"]
        }
    }
    
    # Resolve category details
    cat_details = None
    for k, v in specific_data.items():
        if k in category or category in k:
            cat_details = v
            break
            
    if not cat_details:
        title = category.title().replace("-", " ")
        cat_details = {
            "summaries": [
                f"Results-driven {title} Professional with a proven track record of delivering high-quality performance, streamlining processes, and driving team success in demanding environments.",
                f"Skilled {title} with expertise in modern methodologies, core industry standards, and hands-on execution. Passionate about leveraging technical skills to optimize efficiency.",
                f"Dedicated {title} Specialist offering strong leadership, problem-solving capabilities, and a commitment to continuous professional development."
            ],
            "bullets": [
                f"Spearheaded critical projects in the {title} domain, improving operational workflows and increasing overall execution speed by 20%.",
                f"Designed and implemented strategic initiatives to optimize quality, ensure compliance with standards, and collaborate with cross-functional teams.",
                f"Monitored key metrics and analyzed operational data to resolve complex issues and deliver high-value outcomes.",
                f"Coordinated team projects and implemented process improvements to achieve organizational goals."
            ],
            "skills": [f"{title} Strategy", "Process Optimization", "Team Collaboration", "Problem Solving", "Quality Assurance", "Project Management"]
        }
        
    message_lower = message.lower()
    reply = ""
    commands = {}
    
    if "summary" in message_lower:
        reply = f"Here are 3 professional ATS-friendly summary options for a **{category}** role. Click **Apply Option** to set it:\n\n"
        for i, s in enumerate(cat_details["summaries"]):
            reply += f"**Option {i+1}**:\n*\"{s}\"*\n\n"
        commands["summary"] = cat_details["summaries"]
        
    elif "bullet" in message_lower or "experience" in message_lower or "work" in message_lower or "polish" in message_lower:
        reply = f"Here are strong work experience description bullet points using action verbs for a **{category}** role. Click **Apply Bullets** to append them:\n\n"
        for b in cat_details["bullets"]:
            reply += f"• {b}\n"
        commands["bullets"] = "\n".join([f"- {b}" for b in cat_details["bullets"]])
        
    elif "keyword" in message_lower or "skill" in message_lower:
        reply = f"Here are the top ATS-friendly keywords and core skills recommended for a **{category}** resume. Click **Apply Skills** to update your profile:\n\n"
        reply += ", ".join(cat_details["skills"]) + "\n"
        commands["skills"] = ", ".join(cat_details["skills"])
        
    elif "fill" in message_lower or "sample" in message_lower or "auto-fill" in message_lower:
        reply = f"I've compiled a complete sample resume profile for a professional **{category}** candidate. Click **Apply Sample** to fill the editor!"
        title = category.title().replace("-", " ")
        commands["auto_fill"] = {
            "name": "Alex Johnson",
            "title": f"Senior {title}",
            "email": f"alex.johnson@{category.lower().replace('-', '')}.com",
            "phone": "+1 (555) 019-2834",
            "loc": "San Francisco, CA",
            "link": f"linkedin.com/in/alexjohnson",
            "summary": cat_details["summaries"][0],
            "skills": ", ".join(cat_details["skills"]),
            "experience": [
                {
                    "company": "Aegis Solutions",
                    "role": f"Lead {title}",
                    "date": "2021 - Present",
                    "bullets": "\n".join([f"- {b}" for b in cat_details["bullets"][:3]])
                },
                {
                    "company": "Core Technologies",
                    "role": title,
                    "date": "2018 - 2021",
                    "bullets": "- " + cat_details["bullets"][3] if len(cat_details["bullets"]) > 3 else "- Managed team deliverables."
                }
            ],
            "education": [
                {
                    "school": "Stanford University",
                    "degree": f"M.S. in Computer Science & {title}" if "TECHNOLOGY" in category else f"B.S. in {title}",
                    "date": "2015"
                }
            ]
        }
        
    else:
        # Default conversational advice
        reply = f"Hello! I am your **Aegis AI Resume Writing Assistant** 🤖. I help you write resumes that beat ATS scanners and catch the eye of recruiters.\n\n"
        reply += f"I see your resume matches **{category}** category.\n\n"
        reply += "Here is what I can do for you:\n"
        reply += "1. Click **💡 Generate Summary** to create tailored candidate introductions.\n"
        reply += "2. Click **✍️ Polish Bullets** to write high-impact job duty points using action verbs.\n"
        reply += "3. Click **🎯 Recommend Keywords** to see top ATS terms for your field.\n"
        reply += "4. Click **📋 Auto-Fill Demo** to populate the editor with an optimized sample CV.\n\n"
        reply += "Or type any prompt containing keywords like 'summary', 'bullets', 'skills', or 'fill'!"
        
    return jsonify({
        "reply": reply,
        "commands": commands
    })

@app.route("/", methods=["GET"])
def home():
    return send_from_directory(".", "index.html")

if __name__ == "__main__":
    app.run(debug=True, port=5000)
